//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UI.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MULTITRADER_FORM            101
#define IDS_STRING_DRAW_OPEN            101
#define IDD_TESTCTP01_DIALOG            102
#define DIALOG_LOGIN                    102
#define IDS_STRING_DRAW_MAXPRICE        102
#define IDS_STRING_DRAW_MINPRICE        103
#define IDS_STRING_DRAW_PRECLOSE        104
#define IDS_STRING_DRAW_BUYPRICE01      105
#define IDS_STRING_DRAW_SELLPRICE01     106
#define IDS_STRING_DRAW_LASTPRICE       107
#define IDS_STRING_DRAW_SETTLEMENTPRICE 108
#define IDS_STRING_DRAW_PRESETTLEMENTPRICE 109
#define IDS_STRING_DRAW_BUYCOUNT01      110
#define IDS_STRING_DRAW_SELLCOUNT01     111
#define IDS_STRING_DRAW_OPENINSTREST    112
#define IDS_STRING_DRAW_VOLUME          113
#define IDS_STRING_DRAW_INFO            114
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MultiTraderTYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_STRATEGY_VIEW               159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_CONDITIONORDER_TAB          297
#define IDS_PARKEDORDERACTION_TAB       298
#define IDS_PARKEDORDER_TAB             299
#define IDS_ORDER_TAB                   300
#define IDS_POSITION_TAB                301
#define IDS_TRADED_TAB                  302
#define IDS_UNFILLEDORDER_TAB           303
#define IDS_POSITIONDETAIL_TAB          304
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_CLOSETRADED_TAB             307
#define IDD_FORMVIEW                    310
#define FORMVIEW_STANDARD_MAKEORDER_BOARD 310
#define DIALOG_POSITION                 311
#define DIALOG_CANCELORDER              312
#define DIALOG_QRYCOMMISSIONRATE        313
#define DIALOG_QRYINSTRUMENTMARGINRATE  314
#define DIALOG_QRYEXCHANGERATE          315
#define DIALOG_QRYORDERCOMMRATE         317
#define DIALOG_LINKEXCHANGE             319
#define DIALOG_QRYMAINCONTRACT          320
#define DIALOG_REMOVEPARKEDORDER        323
#define DIALOG_REMOVEPARKEDORDERACTION  325
#define DIALOG_REALTIMEPRICE            326
#define FORMVIEW_STRATEGYSTATUS         327
#define FORMVIEW_STRATEGYMSG            329
#define ID_VIEW_STANDARDMAKEORDERBOARDWND 401
#define IDC_EDIT1                       1000
#define RADIO_BUY                       1000
#define IDC_EDIT2                       1001
#define RADIO_SELL                      1001
#define IDC_COMBO1                      1002
#define IDC_BUTTON1                     1003
#define COMBO_FROMCURRENCYID            1003
#define IDC_BUTTON2                     1004
#define IDC_PROGRESS1                   1005
#define RADIO_CLOSE                     1005
#define IDC_CHECK1                      1006
#define RADIO_OPEN                      1006
#define RADIO_CLOSETODAY                1007
#define BUTTON_OPENCLOSE                1008
#define EDIT_VOLUME                     1009
#define EDIT_STOPPRICE                  1010
#define IDC_SPIN1                       1011
#define SPIN_VOLUME                     1011
#define IDC_SPIN2                       1012
#define SPIN_PRICE                      1012
#define BUTTON_PRICETYPE                1013
#define IDC_BUTTON5                     1014
#define BUTTON_RETSET                   1014
#define BUTTON_ORDER_INSERT             1015
#define COMBO_INSTRUMENTS               1016
#define STATIC_INSTRUMENT               1017
#define STATIC_BUYSELL                  1018
#define EDIT_TRADEPRICE                 1018
#define STATIC_HEDGEFLAG                1018
#define COMBO_EXCHANGE                  1019
#define STATIC_EXCHANGE                 1020
#define EDIT_PRICE                      1021
#define COMBO_TOUCHPRICETYPE            1022
#define CHECK_TOUCHPRICETYPE            1023
#define CHECK_STOPPRICE                 1024
#define COMBO_TimeCondition             1024
#define EDIT_PRICE2                     1025
#define SPIN_TOUCHPRICE                 1025
#define IDC_CHECK4                      1026
#define SPIN_PRICE_TOUCH                1026
#define STATIC_DIRECTION                1027
#define STATIC_TRADETYPE                1028
#define STATIC_TOUCHPRICE               1030
#define STATIC_CONDITIONORDER           1032
#define STATIC_TRADEPRICE2              1033
#define DATETIMEPICKER_GTD              1035
#define BUTTON_TOUCHPRICE_PRICETYPE     1036
#define EDIT_INSTRUMENT                 1039
#define EDIT_DIRECTION                  1040
#define STATIC_CLOSETYPE                1041
#define STATIC_VOLUME                   1045
#define BUTTON_CLOSE                    1048
#define IDC_COMBO2                      1049
#define COMBO_PRICETYPE                 1049
#define STATIC_ORDERSYSIDVALUE          1050
#define COMBO_PRICETYPE_NORMAL          1050
#define STATIC_ORDERSYSID               1051
#define STATIC_INSTRUMENTVALUE          1052
#define STATIC_DIRECTIONVALUE           1053
#define STATIC_OPENCLOSE                1054
#define STATIC_OPENCLOSEVALUE           1055
#define STATIC_VOLUMVALUE               1056
#define STATIC_PRICE                    1057
#define STATIC_PRICEVALUE               1058
#define BUTTON_CANCELORDER              1059
#define COMBO_INSTRUMENT                1060
#define BUTTON_CANCELPARKEDORDER        1060
#define BUTTON_QRY                      1061
#define COMBO_HEDGEFLAG                 1061
#define STATIC_RETURNIMFORMATION        1062
#define STATIC_OPENCOMMISSIONRATE       1063
#define EDIT_OPENCOMMISSIONRATE         1064
#define STATIC_OPENCOMMISSION           1065
#define BUTTON_QRYMARGINRATE            1065
#define EDIT_OPENCOMMISSION             1066
#define STATIC_RETURNMARGINRATE         1066
#define STATIC_CLOSECOMMISSIONRATE      1067
#define STATIC_LongMarginRatioByMoney   1067
#define EDIT_CLOSECOMMISSIONRATE        1068
#define EDIT_LongMarginRatioByMoney     1068
#define STATIC_CLOSECOMMISSION          1069
#define STATIC_LongMarginRatioByVolume  1069
#define STATIC_FROMCURRENCYID           1069
#define EDIT_CLOSECOMMISSION            1070
#define EDIT_LongMarginRatioByVolume    1070
#define STATIC_CLOSETODAYCOMMISSIONRATE 1071
#define STATIC_ShortMarginRatioByMoney  1071
#define STATIC_TOCURRENCYID             1071
#define EDIT_CLOSETODAYCOMMISSIONRATE   1072
#define EDIT_ShortMarginRatioByMoney    1072
#define COMBO_TOCURRENCYID              1072
#define STATIC_CLOSETODAYCOMMISSION     1073
#define STATIC_ShortMarginRatioByVolume 1073
#define BUTTON_QRYEXCHANGERATE          1073
#define EDIT_CLOSETODAYCOMMISSION       1074
#define EDIT_ShortMarginRatioByVolume   1074
#define STATIC_RETURNEXCHANGERATE       1075
#define STATIC_FromCurrencyUnit         1076
#define STATIC_ExchangeRate             1077
#define EDIT_ExchangeRate               1078
#define EDIT_FromCurrencyUnit           1079
#define MFCBUTTON_QRYCOMMRATE           1087
#define STATIC_ORDERCOMMRATE            1091
#define STATIC_OrderCommByVolume        1092
#define STATIC_OrderActionCommByVolume  1093
#define EDIT_OrderCommByVolume          1094
#define EDIT_OrderActionCommByVolume    1095
#define SYSLINK_SHFE                    1096
#define SYSLINK_CFFEX                   1097
#define SYSLINK3_DCE_                   1098
#define STATIC_PRODUCT                  1098
#define SYSLINK_CZCE                    1099
#define COMBO_PRODUCT                   1099
#define SYSLINK_INE                     1100
#define MFCBUTTON_QRYMAINCONTRACT       1100
#define SYSLINK_FUTUREDAILY             1101
#define EDIT_MAINCONTRACT               1101
#define SYSLINK_CTP                     1102
#define STATIC_SPECIFICQRY              1102
#define SYSLINK_SIMNOW                  1103
#define BUTTON_SPECIFICQRYMAINCONTRACT  1103
#define LIST_PRODUCTSET                 1104
#define EDIT_MULTIPLEMAINCONTRACT       1105
#define STATIC_TIP                      1106
#define STATIC_BATCHORDERACTION         1107
#define IDC_MFCBUTTON1                  1108
#define MFCBUTTON_BATCHORDERACTION      1108
#define MFCBUTTON_REMOVEPARKEDORDER     1108
#define MFCBUTTON_START                 1108
#define RADIO_COMMISSION                1110
#define IDC_RADIO2                      1111
#define RADIO_ADVANCE                   1111
#define STATIC_GROUPBOX                 1117
#define STATIC_PRICEDETAIL_SUBBOX1      1118
#define STATIC_PRICEDETAIL_SUBBOX2      1119
#define STATIC_PRICEDETAIL_SUBBOX3      1120
#define STATIC_ASK                      1121
#define STATIC_BID                      1122
#define STATIC_ASKVALUE                 1123
#define STATIC_BIDVALUE                 1124
#define STATIC_GROUPPROFITLOSS          1124
#define STATIC_ASKVOLUME                1125
#define CHECK_PROFITLOSS                1125
#define STATIC_BIDVOLUME                1126
#define RADIO_PROFIT                    1126
#define STATIC_LASTPRICE                1127
#define RADIO_LOSS                      1127
#define STATIC_PreSettlementPrice       1128
#define EDIT_TOUCHPRICE                 1128
#define STATIC_SettlementPrice          1129
#define STATIC_changeprice              1129
#define STATIC_REALTIMEPRICEDISP        1129
#define STATIC_PreClosePrice            1130
#define LIST_STRATEGYSTATUS             1130
#define STATIC_OpenPrice                1131
#define STATIC_STRATEGYNAME             1131
#define STATIC_HighestPrice             1132
#define BUTTON_STOP                     1132
#define STATIC_LowestPrice              1133
#define BUTTON_STOP2                    1133
#define BUTTON_PAUSE                    1133
#define STATIC_STRATEGYMSGBOX           1133
#define STATIC_UpperLimitPrice          1134
#define IDC_LIST1                       1134
#define LIST_STRATEGYMSG                1134
#define STATIC_LowerLimitPrice          1135
#define STATIC_RANGE                    1136
#define STATIC_LASTPRICE_VALUE          1137
#define STATIC_SettlementPrice_value    1138
#define STATIC_AveragePrice_value       1138
#define STATIC_changeprice_value        1138
#define STATIC_UpperLimitPrice_value    1139
#define STATIC_LowerLimitPrice_value    1140
#define STATIC_RANGE_value              1141
#define STATIC_PreSettlementPrice_value 1142
#define STATIC_PreClosePrice_value      1143
#define STATIC_OpenPrice_value          1144
#define STATIC_HighestPrice_value       1145
#define STATIC_LowestPrice_value        1146
#define STATIC_tickInstrument           1147
#define STATIC_ASKVALUE2                1148
#define STATIC_tickExchange             1148
#define ID_WNDCONDITIONORDER            1992
#define ID_WNDPARKEDORDERACTIONLIST     1993
#define ID_WNDPARKEDORDERLIST           1994
#define ID_WNDCLOSETRADE                1995
#define ID_WNDPOSITIONDETAIL            1996
#define ID_WNDUNFILLEDORDERLIST         1997
#define ID_WNDTRADE                     1998
#define ID_WNDPOSITION                  1999
#define ID_WNDORDERLIST                 2000
#define ID_32771                        32771
#define MENU_SYSTEM_LOGIN               32772
#define ID_32773                        32773
#define ID_QRYCOMMISSIONRATE            32774
#define ID_32775                        32775
#define ID_QryInstrumentMarginRate      32776
#define ID_32777                        32777
#define ID_QRYEXCHANGERATE              32778
#define ID_32779                        32779
#define ID_QRYORDERCOMMRATE             32780
#define ID_32781                        32781
#define ID_LINKEXCHANGE                 32782
#define ID_32783                        32783
#define ID_QRY                          32784
#define ID_QRYMAINCONTRACT              32785
#define ID_32786                        32786
#define MENU_SYSTEM_LOGINOUT            32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_REFRESH                      32795
#define ID_32796                        32796
#define ID_OPENFILE                     32797
#define ID_32798                        32798
#define ID_STOPSTRATEGY                 32799
#define ID_INDICATOR_STATICPROFITLOSS   59142
#define ID_INDICATOR_AVAILABLE          59143
#define ID_INDICATOR_CLOSEPROFIT        59144
#define ID_INDICATOR_POSITIONPROFIT     59145
#define ID_INDICATOR_COMMISSION         59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
